// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ThetaDataLike
double ThetaDataLike(double theta, NumericVector kvec, NumericVector lvec, NumericVector nvec, NumericVector cvec);
RcppExport SEXP ThetaMater_ThetaDataLike(SEXP thetaSEXP, SEXP kvecSEXP, SEXP lvecSEXP, SEXP nvecSEXP, SEXP cvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kvec(kvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lvec(lvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ThetaDataLike(theta, kvec, lvec, nvec, cvec));
    return rcpp_result_gen;
END_RCPP
}
// ThetaDataLikeGamma
double ThetaDataLikeGamma(double theta, NumericVector kvec, NumericVector lvec, NumericVector nvec, NumericVector cvec, NumericVector rvec, int Kclasses);
RcppExport SEXP ThetaMater_ThetaDataLikeGamma(SEXP thetaSEXP, SEXP kvecSEXP, SEXP lvecSEXP, SEXP nvecSEXP, SEXP cvecSEXP, SEXP rvecSEXP, SEXP KclassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kvec(kvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lvec(lvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rvec(rvecSEXP);
    Rcpp::traits::input_parameter< int >::type Kclasses(KclassesSEXP);
    rcpp_result_gen = Rcpp::wrap(ThetaDataLikeGamma(theta, kvec, lvec, nvec, cvec, rvec, Kclasses));
    return rcpp_result_gen;
END_RCPP
}
