# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' ThetaDataLike
#' @description
#' Function to compute the probability of a given dataset
#' 
#' @param theta Population parameter to compute the likelihood of the dataset
#' 
#' @param kvec Vector of the mutation counts for each locus
#' 
#' @param lvec Vector of the locus lengths for each locus
#' 
#' @param nvec Vector of the number of samples for each locus
#' 
#' @param cvec Vector of the number of pattern counts
#' 
#' @details
#' \code{ThetaDataLike} Computes the likelihood of a dataset for a given value of theta
#' @export
ThetaDataLike <- function(theta, kvec, lvec, nvec, cvec) {
    .Call('ThetaMater_ThetaDataLike', PACKAGE = 'ThetaMater', theta, kvec, lvec, nvec, cvec)
}

#' @title
#' ThetaDataLikeGamma
#' @description
#' Function to compute the probability of a given dataset
#' 
#' @param theta Population parameter to compute the likelihood of the dataset
#' 
#' @param kvec Vector of the mutation counts for each locus
#' 
#' @param lvec Vector of the locus lengths for each locus
#' 
#' @param nvec Vector of the number of samples for each locus
#' 
#' @param cvec Vector of the number of pattern counts
#' 
#' @details
#' \code{ThetaDataLikeGamma} Computes the likelihood of a dataset for a given value of theta
#' @export
ThetaDataLikeGamma <- function(theta, kvec, lvec, nvec, cvec, rvec, Kclasses) {
    .Call('ThetaMater_ThetaDataLikeGamma', PACKAGE = 'ThetaMater', theta, kvec, lvec, nvec, cvec, rvec, Kclasses)
}

